language: cpp

branches:
   
compiler:
  - clang
  - gcc   
  
os:
  - linux

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq fglrx fglrx-amdcccle
  - sudo apt-get install -qq opencl-headers
  
before_script:
  - chmod +x ./tools/premake4/linux64/premake4
  - ./tools/premake4/linux64/premake4 gmake
  
script:
  - make
  - ./build/UnitTest64D
