language: cpp

branches:
  only:
   - master
   
compiler:
  - clang
  - gcc   
  
os:
  - linux
  
before_script:
  - chmod +x ./tools/premake4/linux64/premake4
  - ./tools/premake4/linux64/premake4 gmake
  
script:
  - make
  - ./build/UnitTest64D
