language: cpp

branches:
   
compiler:
  - clang
  - gcc   
  
os:
  - linux

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq fglrx=2:8.960-0ubuntu1 fglrx-amdcccle
  - sudo apt-get install -qq opencl-headers
  
before_script:
  - chmod +x ./tools/premake4/linux64/premake4
  - ./tools/premake4/linux64/premake4 gmake
  
script:
  - make
  - sudo ./build/UnitTest64D
