name: CI

on: [push]

jobs:
  linux-build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Premake
      run: |
        chmod +x ./tools/premake4/linux64/premake4
        ./tools/premake4/linux64/premake4 gmake
    - name: Make
      run: |
        make
        ./build/UnitTest64D
        echo test, and deploy your project.
  mac-build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Premake
      run: |
        sw_vers -productVersion
        ./tools/premake4/macos/premake4 gmake
    - name: Make
      run: |
        make
        ./build/UnitTest64D
        echo macos.
