name: CI

on: [push]

jobs:
  win-build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1
    - name: Premake
      run: |
        ./tools/premake4/win64/premake5.exe vs2015
    - name: Make
      run: |
        msbuild TravisCITest 
        echo windows. 
        
  linux-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Premake
      run: |
        chmod +x ./tools/premake4/linux64/premake4
        ./tools/premake4/linux64/premake4 gmake
    - name: Make
      run: |
        make
        ./build/UnitTest64D
        echo test, and deploy your project.
  mac-build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Premake
      run: |
        system_profiler SPSoftwareDataType
        ./tools/premake4/macos/premake5 gmake
    - name: Make
      run: |
        make
        ./build/UnitTest64D
        echo macos.
