name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Premake
      run: |
        chmod +x ./tools/premake4/linux64/premake4
        ./tools/premake4/linux64/premake4 gmake
    - name: Make
      run: |
        make
        ./build/UnitTest64D
        echo test, and deploy your project.
        
  build:

    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v1
    - name: Premake
      run: |
        chmod +x ./tools/premake4/linux64/premake4
        ./tools/premake4/linux64/premake4 gmake
    - name: Make
      run: |
        make
        ./build/UnitTest64D
        echo ubuntu-16.04
